language: android
jdk: oraclejdk8

before_install:
 - chmod +x gradlew

android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.1

    # The SDK version used to compile your project
    - android-25

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'android-sdk-build-tools-.+'
    - 'android-sdk-platform-.+'
    
